name: ci-workflow Anna
run-name: Annas ci-workflow
on: [push, workflow_dispatch] # workflow_dispatch: workflow can be triggered manually
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: setup node js 20
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - run: npm ci
      - run: npm run prettier
      - run: npm run typecheck
      - run: npm run test
      - run: npm run build
      - name: Update build artifacts
        uses: actions/upload-pages-artifact@v3 
        with:
          path: 'dist/'
  cd-pipeline: # job that deploys artifact
    runs-on: ubuntu-latest
    needs: ci-pipeline
    permissions: 
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.annasdeployment.outputs.page_url }}
    steps:
      - name: deploy
        id: annasdeployment
        uses: actions/deploy-pages@v4





